# Generated by Django 5.1 on 2025-06-15 18:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='purchased_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время покупки'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('reserved', 'зарезервирован'), ('paid', 'оплачен'), ('cancelled', 'отменён')], default='paid', max_length=10, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
