# Generated by Django 5.1 on 2025-06-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_ticket_purchased_at_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='одобрен модератором'),
        ),
    ]
