# Generated by Django 5.1 on 2025-06-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_review_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='одобрен'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('reserved', 'Зарезервирован'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='paid', max_length=10, verbose_name='статус'),
        ),
    ]
