# Generated by Django 5.1 on 2025-06-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailers/', verbose_name='файл трейлера'),
        ),
    ]
