# Generated by Django 5.1 on 2025-06-23 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_review_is_approved_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BCExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания записи')),
                ('exam_date', models.DateField(verbose_name='дата проведения экзамена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exams/', verbose_name='задание (картинка)')),
                ('is_public', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('students', models.ManyToManyField(blank=True, related_name='bc_exams', to=settings.AUTH_USER_MODEL, verbose_name='студенты')),
            ],
            options={
                'verbose_name': 'экзамен BC',
                'verbose_name_plural': 'экзамены BC',
                'ordering': ['-exam_date', 'title'],
            },
        ),
    ]
